"""empty message

Revision ID: 007ad22c7dee
Revises: 0f09faa92a54
Create Date: 2024-02-08 14:41:03.489493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007ad22c7dee'
down_revision = '0f09faa92a54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
