"""empty message

Revision ID: 0f09faa92a54
Revises: f56275c9c15d
Create Date: 2024-02-08 12:56:11.522336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f09faa92a54'
down_revision = 'f56275c9c15d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
