"""empty message

Revision ID: f56275c9c15d
Revises: 1d43003b7730
Create Date: 2024-02-08 12:49:09.452105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56275c9c15d'
down_revision = '1d43003b7730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
